version: "6.0"
servers:
  - id: foo
    type: smtp
    phases:
      eod:
        hook: foo
    transport: file-deliver
  - id: bar
    type: plugin
    phases:
      eod:
        hook: bar
    transport: mx
  - id: baz
    type: plugin
    phases:
      eod:
        hook: baz
    transport: mx
transportgroups:
  - id: default
    retry:
      count: 30
      intervals:
        - interval: 60
        - interval: 900
        - interval: 3600
          notify: true
        - interval: 7200
        - interval: 10800
    dsn:
      transport: mx
    transports:
      - id: mx
        session:
          tls:
            mode: dane
      - id: file-deliver
        connection:
          server: 0.0.0.0
resolver:
  cache:
    size: 10000
